import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MetricCard, LoadingSpinner, ErrorAlert } from '../components/UI';
import { RiskDistributionChart, RiskBreakdownChart, SignalHeatmap, } from '../components/Charts';
import { AlertTriangle, Activity, Database } from 'lucide-react';
export const CommandCenter = ({ scores, stats, loading, error, }) => {
    if (loading)
        return _jsx(LoadingSpinner, { message: "Loading detection engine..." });
    if (error)
        return _jsx(ErrorAlert, { title: "Error Loading Data", message: error.message });
    if (!scores.length)
        return _jsx(ErrorAlert, { title: "No Data", message: "No accounts to display" });
    const criticalCount = scores.filter((s) => s.risk_level === 'CRITICAL').length;
    const highCount = scores.filter((s) => s.risk_level === 'HIGH').length;
    const mediumCount = scores.filter((s) => s.risk_level === 'MEDIUM').length;
    const lowCount = scores.filter((s) => s.risk_level === 'LOW').length;
    const avgScore = scores.reduce((sum, s) => sum + s.risk_score, 0) / scores.length;
    return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-5 gap-4", children: [_jsx(MetricCard, { label: "\uD83D\uDD34 CRITICAL", value: criticalCount, riskLevel: "CRITICAL" }), _jsx(MetricCard, { label: "\uD83D\uDFE0 HIGH RISK", value: highCount, riskLevel: "HIGH" }), _jsx(MetricCard, { label: "\uD83D\uDFE1 MEDIUM", value: mediumCount, riskLevel: "MEDIUM" }), _jsx(MetricCard, { label: "\uD83D\uDFE2 LOW", value: lowCount, riskLevel: "LOW" }), _jsx(MetricCard, { label: "\uD83D\uDCC8 AVG SCORE", value: avgScore.toFixed(0), className: "border-blue-600 bg-blue-950" })] }), stats && (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-4 gap-4", children: [_jsx("div", { className: "bg-slate-800 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Database, { className: "text-blue-400", size: 24 }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-sm", children: "Total Accounts" }), _jsx("p", { className: "text-2xl font-bold text-white", children: stats.total_accounts })] })] }) }), _jsx("div", { className: "bg-slate-800 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Activity, { className: "text-green-400", size: 24 }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-sm", children: "Transactions" }), _jsx("p", { className: "text-2xl font-bold text-white", children: stats.total_transactions })] })] }) }), _jsx("div", { className: "bg-slate-800 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(AlertTriangle, { className: "text-yellow-400", size: 24 }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-sm", children: "Devices" }), _jsx("p", { className: "text-2xl font-bold text-white", children: stats.total_devices })] })] }) }), _jsx("div", { className: "bg-slate-800 rounded-lg p-4", children: _jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Activity, { className: "text-purple-400", size: 24 }), _jsxs("div", { children: [_jsx("p", { className: "text-gray-400 text-sm", children: "Network" }), _jsxs("p", { className: "text-lg font-bold text-white", children: [stats.network_nodes, " nodes"] })] })] }) })] })), _jsxs("div", { className: "grid grid-cols-1 lg:grid-cols-3 gap-6", children: [_jsx("div", { className: "lg:col-span-2", children: _jsx(RiskDistributionChart, { scores: scores }) }), _jsx("div", { children: _jsx(RiskBreakdownChart, { critical: criticalCount, high: highCount, medium: mediumCount, low: lowCount }) })] }), _jsx("div", { children: _jsx(SignalHeatmap, { scores: scores, limit: 20 }) })] }));
};
